services:
  traefik:
    image: traefik:v3.6
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=contact@fiestaaa.app
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_API_VERSION=${DOCKER_API_VERSION:-1.52}
    ports: ["80:80", "443:443"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    restart: unless-stopped

  db:
    image: postgres:18
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

  api:
    image: ghcr.io/theopeuchlestrade/fiestaaa_back:latest
    env_file: .env
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      AVATAR_UPLOAD_DIR: /data/uploads/avatars
      AVATAR_BASE_URL: https://api.fiestaaa.app/media/avatars
      FCM_SERVICE_ACCOUNT_PATH: /app/service-account.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/service-account.json:/app/service-account.json:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.fiestaaa.app`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.services.api.loadbalancer.server.port=8080
    restart: unless-stopped

  front:
    image: ghcr.io/theopeuchlestrade/fiestaaa_front:latest
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`fiestaaa.app`)
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.routers.front.tls.certresolver=le
      - traefik.http.services.front.loadbalancer.server.port=80 # adapte si front écoute ailleurs
    depends_on:
      - api
    restart: unless-stopped
