use utoipa::OpenApi;

use crate::models::{
    AddressSuggestion, CompleteRegistrationPayload, DeviceDeletePayload, DeviceRefreshPayload,
    DeviceRegisterPayload, ErrorResponse, Event, EventCustomItemPayload, EventExpenseBalanceView,
    EventExpenseParticipantView, EventExpensePayload, EventExpenseSettlementView, EventExpenseView,
    EventExpensesSummaryView, EventItemAttachPayload, EventItemReservationPayload, EventItemView,
    EventPatchPayload, EventPayload, EventPollCreatePayload, EventPollVotePayload, Friend,
    FriendRequest, FriendRequestActionPayload, FriendRequestPayload, FriendSearchResult,
    HandleAvailabilityResponse, HandleUpdatePayload, HealthResponse, Invitation,
    InvitationPatchPayload, InvitationPayload, Item, ItemContribution, ItemPatchPayload,
    ItemPayload, LoginPayload, MeResponse, PaymentProvider, PaymentProviderPatchPayload,
    PaymentProviderPayload, PollOptionView, PollOptionVoter, PollView, RealtimeTicketResponse,
    RegisterPayload, StatusResponse, TokenResponse, VerifyEmailPayload,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::root::hello,
        crate::routes::root::me,
        crate::routes::auth::register,
        crate::routes::auth::verify_email,
        crate::routes::auth::complete_registration,
        crate::routes::auth::login,
        crate::routes::auth::oauth_login,
        crate::routes::auth::logout,
        crate::routes::health::health,
        crate::routes::events::get_event,
        crate::routes::items::list_items,
        crate::routes::items::create_item,
        crate::routes::items::replace_item,
        crate::routes::items::update_item,
        crate::routes::items::delete_item,
        crate::routes::events::list_events,
        crate::routes::events::create_event,
        crate::routes::events::replace_event,
        crate::routes::events::update_event,
        crate::routes::events::delete_event,
        crate::routes::events::search_address,
        crate::routes::events::list_event_items,
        crate::routes::events::attach_event_item,
        crate::routes::events::reserve_event_item,
        crate::routes::events::delete_event_item,
        crate::routes::events::list_event_item_contributions,
        crate::routes::events::create_custom_event_item,
        crate::routes::events::list_event_polls,
        crate::routes::events::create_event_poll,
        crate::routes::events::vote_event_poll,
        crate::routes::events::delete_event_poll,
        crate::routes::events::list_event_expenses,
        crate::routes::events::create_event_expense,
        crate::routes::events::delete_event_expense,
        crate::routes::events::get_event_expenses_summary,
        crate::routes::invitations::list_event_invitations,
        crate::routes::invitations::create_invitation,
        crate::routes::invitations::delete_invitation,
        crate::routes::invitations::list_my_invitations,
        crate::routes::invitations::respond_invitation,
        crate::routes::friends::list_friends,
        crate::routes::friends::search_friends,
        crate::routes::friends::create_friend_request,
        crate::routes::friends::list_friend_requests,
        crate::routes::friends::respond_friend_request,
        crate::routes::friends::delete_friend,
        crate::routes::notifications::register_device,
        crate::routes::notifications::refresh_device,
        crate::routes::notifications::delete_device,
        crate::routes::realtime::issue_realtime_ticket,
        crate::routes::users::check_handle_availability,
        crate::routes::users::update_handle,
        crate::routes::payment_providers::list_payment_providers,
        crate::routes::payment_providers::create_payment_provider,
        crate::routes::payment_providers::replace_payment_provider,
        crate::routes::payment_providers::update_payment_provider,
        crate::routes::payment_providers::delete_payment_provider
    ),
    components(
        schemas(
            LoginPayload,
            RegisterPayload,
            VerifyEmailPayload,
            CompleteRegistrationPayload,
            StatusResponse,
            TokenResponse,
            ErrorResponse,
            MeResponse,
            HealthResponse,
            Item,
            ItemPayload,
            ItemPatchPayload,
            Event,
            EventPayload,
            EventPatchPayload,
            EventItemView,
            EventItemAttachPayload,
            EventItemReservationPayload,
            EventCustomItemPayload,
            EventExpensePayload,
            EventExpenseParticipantView,
            EventExpenseView,
            EventExpenseBalanceView,
            EventExpenseSettlementView,
            EventExpensesSummaryView,
            Invitation,
            InvitationPayload,
            InvitationPatchPayload,
            ItemContribution,
            EventPollCreatePayload,
            EventPollVotePayload,
            PollOptionView,
            PollOptionVoter,
            PollView,
            Friend,
            FriendSearchResult,
            FriendRequestPayload,
            FriendRequestActionPayload,
            FriendRequest,
            HandleAvailabilityResponse,
            HandleUpdatePayload,
            PaymentProvider,
            PaymentProviderPayload,
            PaymentProviderPatchPayload,
            AddressSuggestion,
            DeviceRegisterPayload,
            DeviceRefreshPayload,
            DeviceDeletePayload,
            RealtimeTicketResponse
        )
    ),
    tags(
        (name = "root", description = "General endpoints"),
        (name = "auth", description = "Authentication"),
        (name = "health", description = "API monitoring"),
        (name = "items", description = "Referenced item catalog"),
        (name = "events", description = "Event management"),
        (name = "invitations", description = "Event invitation management"),
        (name = "friends", description = "Friend and request management"),
        (name = "users", description = "User and handle management"),
        (name = "payment-providers", description = "Payment provider configuration (admin)"),
        (name = "notifications", description = "Device registration for push notifications")
    )
)]
pub struct ApiDoc;
