use utoipa::OpenApi;

use crate::models::{
    AddressSuggestion, DeviceRefreshPayload, DeviceRegisterPayload, ErrorResponse, Event,
    EventCustomItemPayload, EventItemAttachPayload, EventItemReservationPayload, EventItemView,
    EventPatchPayload, EventPayload, EventPollCreatePayload, EventPollVotePayload, Friend,
    FriendRequest, FriendRequestActionPayload, FriendRequestPayload, FriendSearchResult,
    HandleAvailabilityResponse, HandleUpdatePayload, HealthResponse, Invitation,
    InvitationPatchPayload, InvitationPayload, Item, ItemContribution, ItemPatchPayload,
    ItemPayload, LoginPayload, MeResponse, PaymentProvider, PaymentProviderPatchPayload,
    PaymentProviderPayload, PollOptionView, PollOptionVoter, PollView, RegisterPayload,
    StatusResponse, TokenResponse,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::root::hello,
        crate::routes::root::me,
        crate::routes::auth::register,
        crate::routes::auth::login,
        crate::routes::auth::oauth_login,
        crate::routes::health::health,
        crate::routes::events::get_event,
        crate::routes::items::list_items,
        crate::routes::items::create_item,
        crate::routes::items::replace_item,
        crate::routes::items::update_item,
        crate::routes::items::delete_item,
        crate::routes::events::list_events,
        crate::routes::events::create_event,
        crate::routes::events::replace_event,
        crate::routes::events::update_event,
        crate::routes::events::delete_event,
        crate::routes::events::search_address,
        crate::routes::events::list_event_items,
        crate::routes::events::attach_event_item,
        crate::routes::events::reserve_event_item,
        crate::routes::events::delete_event_item,
        crate::routes::events::list_event_item_contributions,
        crate::routes::events::create_custom_event_item,
        crate::routes::events::list_event_polls,
        crate::routes::events::create_event_poll,
        crate::routes::events::vote_event_poll,
        crate::routes::events::delete_event_poll,
        crate::routes::invitations::list_event_invitations,
        crate::routes::invitations::create_invitation,
        crate::routes::invitations::delete_invitation,
        crate::routes::invitations::list_my_invitations,
        crate::routes::invitations::respond_invitation,
        crate::routes::friends::list_friends,
        crate::routes::friends::search_friends,
        crate::routes::friends::create_friend_request,
        crate::routes::friends::list_friend_requests,
        crate::routes::friends::respond_friend_request,
        crate::routes::friends::delete_friend,
        crate::routes::notifications::register_device,
        crate::routes::notifications::refresh_device,
        crate::routes::notifications::delete_device,
        crate::routes::users::check_handle_availability,
        crate::routes::users::update_handle,
        crate::routes::payment_providers::list_payment_providers,
        crate::routes::payment_providers::create_payment_provider,
        crate::routes::payment_providers::replace_payment_provider,
        crate::routes::payment_providers::update_payment_provider,
        crate::routes::payment_providers::delete_payment_provider
    ),
    components(
        schemas(
            LoginPayload,
            RegisterPayload,
            StatusResponse,
            TokenResponse,
            ErrorResponse,
            MeResponse,
            HealthResponse,
            Item,
            ItemPayload,
            ItemPatchPayload,
            Event,
            EventPayload,
            EventPatchPayload,
            EventItemView,
            EventItemAttachPayload,
            EventItemReservationPayload,
            EventCustomItemPayload,
            Invitation,
            InvitationPayload,
            InvitationPatchPayload,
            ItemContribution,
            EventPollCreatePayload,
            EventPollVotePayload,
            PollOptionView,
            PollOptionVoter,
            PollView,
            Friend,
            FriendSearchResult,
            FriendRequestPayload,
            FriendRequestActionPayload,
            FriendRequest,
            HandleAvailabilityResponse,
            HandleUpdatePayload,
            PaymentProvider,
            PaymentProviderPayload,
            PaymentProviderPatchPayload,
            AddressSuggestion,
            DeviceRegisterPayload,
            DeviceRefreshPayload
        )
    ),
    tags(
        (name = "root", description = "Endpoints généraux"),
        (name = "auth", description = "Authentification"),
        (name = "health", description = "Surveillance de l'API"),
        (name = "items", description = "Catalogue des items référencés"),
        (name = "events", description = "Gestion des événements"),
        (name = "invitations", description = "Gestion des invitations aux événements"),
        (name = "friends", description = "Gestion des amis et demandes"),
        (name = "users", description = "Gestion des utilisateurs et handles"),
        (name = "payment-providers", description = "Configuration des fournisseurs de paiement (admin)"),
        (name = "notifications", description = "Enregistrement des devices pour les notifications push")
    )
)]
pub struct ApiDoc;
